# Basic Python

## 1. Split this string

In [103]:
s = "Hi there Sam!"

In [104]:
a=s.split()
a

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [105]:
planet = "Earth"
diameter = 12742

In [106]:



result="The diameter of "+ format(planet)+ " is " + format(diameter)+ " Kilometers "
result

'The diameter of Earth is 12742 Kilometers '

## 3. In this nest dictionary grab the word "hello"

In [107]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}


In [108]:
d

d['k1'][3]['tricky'][3]['target'][3]


'hello'

# Numpy

In [109]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [110]:
a1=np.zeros(10)
print("The array of 10 Zeros is",a1)

The array of 10 Zeros is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [111]:
a2=np.ones(10)*5
print("The array of 10 fives is ",a2)

The array of 10 fives is  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [112]:
a3=np.arange(20,35,2)
print("The all even Integers number is:\n  " ,a3)

The all even Integers number is:
   [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [113]:
a4=np.arange(0,9).reshape(3,3)
a4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [114]:
# 1-d arrays in row wise vstack returns 2 d
a=np.array([1,2,3])
b=np.array([4,5,6])
a5=np.vstack((a,b))
a5
print("-----------------------------------")

# concatinate a and b
a6=np.concatenate((a,b))
a6

-----------------------------------


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [115]:
import pandas as pd


In [116]:
data=[['virat','India',36],['MSD','India',40]]
df=pd.DataFrame(data,columns=['Cricket_Player_Name','Country','Age'])
df

Cricket_Player_Name Country  Age
0               virat   India   36
1                 MSD   India   40

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [117]:
n1=pd.date_range("01-01-2023","10-02-2023")
n2=pd.Series(n1)

n2

0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...    
270   2023-09-28
271   2023-09-29
272   2023-09-30
273   2023-10-01
274   2023-10-02
Length: 275, dtype: datetime64[ns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [118]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [119]:
df=pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24